config/routes.rb
Rails.application.routes.draw do
  get 'android/feeds' => 'feeds#index'

  post 'android/create_live' => 'android_live#create'
  delete 'android/live/:movie_id' => 'android_live#delete'

  resources :rooms
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/room.rb
class Room < ApplicationRecord
end

app/controllers/android_abstract_controller.rb
class AndroidAbstractController < ApplicationController
  protect_from_forgery with: :null_session
  layout false
  before_filter :set_content_type

  include Exceptions

  rescue_from Exceptions::ParameterNotFulfilled do
    render json: { error_message: 'parameter_not_fulfilled' }, status: 412
  end

  rescue_from Exceptions::GoogleAccountNotVerified do
    render json: { error_message: 'google_account_not_verified'}, status: 401
  end

  rescue_from Exceptions::PushRegistrationFailed do
    render json: { error_message: 'push_registration_failed' }, status: 500
  end

  rescue_from Exceptions::UserUnAuthorized do
    render json: { error_message: 'user_unauthorized' }, status: 401
  end

  rescue_from Exceptions::UserFieldDuplicated do
    render json: { error_message: 'user_field_duplicated' }, status: 406
  end

  rescue_from Exceptions::CannotCreateRoom do
    render json: { error_message: 'cannot create room. retry again' }, status: 413
  end

  rescue_from Exceptions::CannotDeleteApplication do
    render json: { error_message: 'cannot delete room. retry again' }, status: 413
  end

  def set_content_type
    self.content_type = 'application/json'
  end
end

app/controllers/android_live_controller.rb
class AndroidLiveController < AndroidAbstractController

  PRD_SERVER_HOST_ADDRESS = 'prd_server_addres'
  DEV_SERVER_HOST_ADDRESS = 'http://localhost'

  def create
    room_name = params[:room_name]
    if room_name.nil?
      raise Exceptions::ParameterNotFulfilled
    end

    @room = Room.create(room_name: room_name)
    live_server = LIVE_SERVER::LiveServer.new(@room.id)
    res = live_server.create_application
    if !res.code.eql? 201
      raise Exceptions::CannotCreateRoom
    end

    live_url = live_server.make_live_url
    @room.stream_url = live_url
    @room.app_name = @room.id
    @room.save
  end

  def delete
    @movie_id = params[:movie_id]
    movie = Room.find(@movie_id)
    if movie.nil?
      raise Exceptions::ParameterNotFulfilled
    end

    app_name = movie.app_name
    unless app_name.nil?
      live_server = LIVE_SERVER::LiveServer.new(app_name)
      res = live_server.delete_application
      if !res.code.eql? 200
        raise Exceptions::CannotDeleteApplication
      end
    end

    movie.delete
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/feeds_controller.rb
class FeedsController < ApplicationController
  def index
    @feeds = Room.all
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController
  before_action :set_room, only: [:show, :edit, :update, :destroy]

  # GET /rooms
  # GET /rooms.json
  def index
    @rooms = Room.all
  end

  # GET /rooms/1
  # GET /rooms/1.json
  def show
  end

  # GET /rooms/new
  def new
    @room = Room.new
  end

  # GET /rooms/1/edit
  def edit
  end

  # POST /rooms
  # POST /rooms.json
  def create
    @room = Room.new(room_params)

    respond_to do |format|
      if @room.save

        live_server = LIVE_SERVER::LiveServer.new(@room.id)
        res = live_server.create_application

        format.html { redirect_to @room, notice: 'Room was successfully created.' }
        format.json { render :show, status: :created, location: @room }
      else
        format.html { render :new }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /rooms/1
  # PATCH/PUT /rooms/1.json
  def update
    respond_to do |format|
      if @room.update(room_params)
        format.html { redirect_to @room, notice: 'Room was successfully updated.' }
        format.json { render :show, status: :ok, location: @room }
      else
        format.html { render :edit }
        format.json { render json: @room.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /rooms/1
  # DELETE /rooms/1.json
  def destroy
    app_name = @room.app_name

    live_server = LIVE_SERVER::LiveServer.new(app_name)
    res = live_server.delete_application

    @room.destroy
    respond_to do |format|
      format.html { redirect_to rooms_url, notice: 'Room was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_room
      @room = Room.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def room_params
      params.require(:room).permit(:stream_url, :room_name)
    end
end

app/helpers/android_live_helper.rb
module AndroidLiveHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/feeds_helper.rb
module FeedsHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/views/feeds/index.html.erb
<h1>Feeds#index</h1>
<p>Find me in app/views/feeds/index.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>LiveCastServer</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/rooms/_form.html.erb
<%= form_for(room) do |f| %>
  <% if room.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(room.errors.count, "error") %> prohibited this room from being saved:</h2>

      <ul>
      <% room.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :stream_url %>
    <%= f.text_field :stream_url %>
  </div>

  <div class="field">
    <%= f.label :room_name %>
    <%= f.text_field :room_name %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/rooms/edit.html.erb
<h1>Editing Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Show', @room %> |
<%= link_to 'Back', rooms_path %>

app/views/rooms/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Rooms</h1>

<table>
  <thead>
    <tr>
      <th>Stream url</th>
      <th>Room name</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @rooms.each do |room| %>
      <tr>
        <td><%= room.stream_url %></td>
        <td><%= room.room_name %></td>
        <td><%= link_to 'Show', room %></td>
        <td><%= link_to 'Edit', edit_room_path(room) %></td>
        <td><%= link_to 'Destroy', room, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Room', new_room_path %>

app/views/rooms/new.html.erb
<h1>New Room</h1>

<%= render 'form', room: @room %>

<%= link_to 'Back', rooms_path %>

app/views/rooms/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Stream url:</strong>
  <%= @room.stream_url %>
</p>

<p>
  <strong>Room name:</strong>
  <%= @room.room_name %>
</p>

<%= link_to 'Edit', edit_room_path(@room) %> |
<%= link_to 'Back', rooms_path %>